_wandb:
    value:
        cli_version: 0.18.5
        m: []
        python_version: 3.10.13
        t:
            "1":
                - 1
                - 41
                - 49
                - 55
                - 63
            "2":
                - 1
                - 41
                - 49
                - 55
                - 63
            "3":
                - 1
                - 13
                - 16
                - 23
                - 55
            "4": 3.10.13
            "5": 0.18.5
            "8":
                - 5
                - 9
            "12": 0.18.5
            "13": linux-x86_64
ThreeAugment:
    value: false
aa:
    value: rand-m9-mstd0.5-inc1
attn_only:
    value: false
batch_size:
    value: 20
bce_loss:
    value: false
clip_grad:
    value: null
color_jitter:
    value: 0.3
cooldown_epochs:
    value: 10
cosub:
    value: false
cutmix:
    value: 1
cutmix_minmax:
    value: null
data_path:
    value: /data/ILSVRC2012
data_set:
    value: IMNET
ddp_dist_url:
    value: tcp://gpusvr021321:6006
ddp_rank:
    value: 0
ddp_world_size:
    value: 1
decay_epochs:
    value: 30
decay_rate:
    value: 0.1
dev_device:
    value: cuda:0
dev_device_id:
    value: 0
dev_num_gpus:
    value: 1
device:
    value: cuda
dist_eval:
    value: false
dist_url:
    value: env://
distillation_alpha:
    value: 0.5
distillation_tau:
    value: 1
distillation_type:
    value: none
distributed:
    value: true
drop:
    value: 0
drop_path:
    value: 0.1
epochs:
    value: 90
eval:
    value: false
eval_crop_ratio:
    value: 0.875
finetune:
    value: ""
inat_category:
    value: name
input_size:
    value: 224
lr:
    value: 0.0005
lr_noise:
    value: null
lr_noise_pct:
    value: 0.67
lr_noise_std:
    value: 1
min_lr:
    value: 1e-05
mixup:
    value: 0.8
mixup_mode:
    value: batch
mixup_prob:
    value: 1
mixup_switch_prob:
    value: 0.5
model:
    value: fourbits_deit_small_patch16_224
model_ema:
    value: true
model_ema_decay:
    value: 0.99996
model_ema_force_cpu:
    value: false
momentum:
    value: 0.9
nb_classes:
    value: 1000
num_workers:
    value: 10
opt:
    value: adamw
opt_betas:
    value: null
opt_eps:
    value: 1e-08
output_dir:
    value: output/finegrained_wgfp_qkl_vertex_white_token
patience_epochs:
    value: 10
pin_mem:
    value: true
recount:
    value: 1
remode:
    value: pixel
repeated_aug:
    value: false
reprob:
    value: 0.25
resplit:
    value: false
resume:
    value: ""
sched:
    value: cosine
seed:
    value: 0
smoothing:
    value: 0.1
src:
    value: false
start_epoch:
    value: 0
teacher_model:
    value: regnety_160
teacher_path:
    value: ""
train_interpolation:
    value: bicubic
train_mode:
    value: true
unscale_lr:
    value: false
warmup_epochs:
    value: 5
warmup_lr:
    value: 1e-06
weight_decay:
    value: 0.05
world_size:
    value: 4
